version: '2'
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:5.2
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:5.2
    links:
      - "elasticsearch"
    ports:
      - "80:5601"

